### ISSUE TITLE
Missing csi image

### ISSUE THREAD

**Issue by fondemen** [kvaps/kube-linstor#12]
Hello !
docker.io/kvaps/linstor-csi:v1.7.1-2 and docker.io/kvaps/linstor-csi:v1.7.1-1 are missing from docker repositories
It breaks the 1.17.1-+ release.
Regards,

**Comment by kvaps** [comment]
Thanks for report! Images are built:

`v1.7.1-1` based on `linstor-csi:v0.8.2`
`v1.7.1-2` based on `linstor-csi:v0.8.3` with latest rebase of resizing feature branch https://github.com/piraeusdatastore/linstor-csi/pull/70

see https://github.com/piraeusdatastore/linstor-csi/issues/68#issuecomment-641886034 for changelog
