### ISSUE TITLE
Error: failed to download "kvaps/kube-linstor"

### ISSUE THREAD

**Issue by tobg** [kvaps/kube-linstor#16]
Hello, tried to follow the read.me. Everything is working except the following:

helm install linstor01 kvaps/kube-linstor --version 1.7.2 \
  --namespace linstor \
  -f linstor.yaml

Error: failed to download "kvaps/kube-linstor" (hint: running `helm repo update` may help)

**Comment by tobg** [comment]
This should do the trick. Hope this is correct.?

It is linstor not kube-linstor

helm install linstor kvaps/linstor --version 1.7.2 \
  --namespace linstor \
  -f linstor.yaml

**Comment by kvaps** [comment]
Hi, I've not released 1.8.0 version yet due amount of issues:

- https://github.com/LINBIT/linstor-server/issues/172
- https://github.com/LINBIT/linstor-server/issues/171
- https://github.com/LINBIT/linstor-server/issues/179

If you want 1.8.0, try installing it locally from the devel branch.


```
helm install linstor helm/kube-linstor --namespace linstor -f examples/linstor.yaml
```
where `helm/kube-linstor` is path to https://github.com/kvaps/kube-linstor/tree/devel/helm/kube-linstor

there is used modified image with fixes from this post https://github.com/LINBIT/linstor-server/issues/171#issuecomment-677173509

**Comment by tobg** [comment]
Oh sorry. My fault. I tried it with 1.7.2 and also with 1.8.0. I corrected my initial post.

**Comment by kvaps** [comment]
I see, yep, seems simple typo in chart name.
Last week I prepared helm repository and updated instruction to install chart from it instead of cloning git repository.

Fixed in https://github.com/kvaps/kube-linstor/commit/f99f3b31fde8356faf555de3fa67b6c9ccd11488. Thanks for the report!
