### ISSUE TITLE
The satellite does not support the device provider LVM_THIN

### ISSUE THREAD

**Issue by tobg** [kvaps/kube-linstor#17]
Is thin provisioning supported?

Tried:
linstor storage-pool create lvmthin k8w1 linstor-pool vg/lvmthinpool

and got:
ERROR:
    The satellite does not support the device provider LVM_THIN

Kuberenetes node does support it. I tried with local linstor command.

**Comment by kvaps** [comment]
Yes, we're using lvmthin for our nodes, do you have node `ONLINE`?

**Comment by tobg** [comment]
You mean the pods?

**Comment by kvaps** [comment]
No, check the output of `linstor node list` command, I guess your node is `Offline` for some reason

**Comment by tobg** [comment]
Your right:  OFFLINE(VERSION MISMATCH)
Could it be the kernel module drdb version on worker node?

**Comment by tobg** [comment]
I use the following versions:

drbd-dkms is already the newest version (9.0.24-1ppa1~bionic1)
drbd-utils is already the newest version (9.13.1-1ppa1~bionic1)

**Comment by kvaps** [comment]
This is happening with different versions of linstor-controller and linstor-satelite, what chart did you used in the end?

**Comment by tobg** [comment]
This one:

# download example values
curl -LO https://github.com/kvaps/kube-linstor/raw/master/examples/linstor.yaml

# install release
helm install linstor kvaps/linstor --version 1.7.2 \
  --namespace linstor \
  -f linstor.yaml

**Comment by tobg** [comment]
It's not clear to me if I have to use the pods named satalite or the nodes on which kubernetes is running

linstor node create node1 10.0.0.1

**Comment by kvaps** [comment]
Weird indeed 🤔

chart uses correct images:
```bash
helm template linstor kvaps/linstor --version 1.7.2 | grep image: | grep 'kvaps/linstor'
```

there is correct versions inside the image:

```bash
# docker run -ti --rm docker.io/kvaps/linstor-controller:v1.7.2-3
LINSTOR, Module Controller
Version:            1.7.2.1-7500524b9 (7500524b9d7ff6ca697efe357c4031186642a9dc)
Build time:         2020-07-20T09:26:31+00:00
Java Version:       11
Java VM:            Debian, Version 11.0.7+10-post-Debian-3deb10u1
Operating system:   Linux, Version 5.6.3-arch1-1
Environment:        amd64, 8 processors, 1894 MiB memory reserved for allocations
```

```bash
# docker run -ti --rm docker.io/kvaps/linstor-satellite:v1.7.2
LINSTOR, Module Satellite
Version:            1.7.2 (7cdf6b63ece868897519e2268ca7c2daac09de44)
Build time:         2020-07-13T09:34:24+00:00
Java Version:       11
Java VM:            Debian, Version 11.0.7+10-post-Debian-3deb10u1
Operating system:   Linux, Version 5.6.3-arch1-1
Environment:        amd64, 8 processors, 1894 MiB memory reserved for allocations
```

could you show me the output of:

```bash
kubectl get -n linstor sts/linstor-linstor-controller ds/linstor-linstor-satellite
```

and

```bash
kubectl get -n linstor sts/linstor-linstor-controller ds/linstor-linstor-satellite -o yaml | grep image:
```

please?

**Comment by kvaps** [comment]
> It's not clear to me if I have to use the pods named satalite or the nodes on which kubernetes is running
> 
> linstor node create node1 10.0.0.1

You should name nodes the same way like they are named in kubernetes eg:

```
kubectl get node -o wide
NAME   STATUS   ROLES     AGE    VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION   CONTAINER-RUNTIME
m9c4   Ready    hosting   660d   v1.17.1   10.36.129.139   <none>        Ubuntu 18.04.3 LTS   4.15.18-24-pve   docker://19.3.5
```

you should use:

```
linstor node create m9c4 10.36.129.139 --communication-type SSL
```

**Comment by tobg** [comment]
Thank you. I used the nodes as you described. kubernetes is 1.18.6. 

Update:
It is working now. Did not add "--communication-type SSL" that was the issue.

Thank you very much for all your support!
