### ISSUE TITLE
Names changed in v1.9.0 helm chart

### ISSUE THREAD

**Issue by fondemen** [kvaps/kube-linstor#18]
Hello there!

I'm not sure whether it's intentional or not, but some names changed on the helm chart, e.g. linstor-linstor-controller became linstor-controller. I've upgraded using command `helm -n linstor upgrade linstor kvaps/linstor -f linstor.yaml`.

This implies changing some script on my side (`alias linstor='kubectl exec -n linstor linstor-controller-0 -c linstor-controller -- linstor'`), but it also prevents linstor starting up (linstor-csi-node, linstor-satellite, linstor-controller and linstor-csi-controller cannot find secret linstor-client-tls). I managed to start my cluster again by changing linstor-client-tls to the existing linstor-linstor-client-tls secret refernced in the above-mentioned damonsets/statefulset.

Regards!

**Comment by fondemen** [comment]
I could get it back to normal work by adding  `fullnameOverride: linstor-linstor` in the values file...

**Comment by kvaps** [comment]
Hehe that's true, I probably need to update commands in README.md file.

By the way, the name change shouldn't break anything, you can even fully remove the release and install it again.

**Comment by kvaps** [comment]
Documentation updated! Thanks for the report.

> it also prevents linstor starting up (linstor-csi-node, linstor-satellite, linstor-controller and linstor-csi-controller cannot find secret linstor-client-tls

Unfortunately I can't reproduce this, could you tell me more about your environment / installation method?
