### ISSUE TITLE
function "mustToJson" not defined  on 1.11.1-3

### ISSUE THREAD

**Issue by bratao** [kvaps/kube-linstor#36]
Hello, I tried to update/ fresh install the 1.11.1-3 and i´m facing this error:

`Wait helm template failed. Error: render error in "linstor/templates/configurator-configmap.yaml": template: linstor/templates/configurator-configmap.yaml:12:8: executing "linstor/templates/configurator-configmap.yaml" at <tpl (.Files.Get "scripts/configurator.controller") .>: error calling tpl: Error during tpl function execution for "#!/bin/bash\nset -e\n. $(dirname $0)/functions.sh\n\nload_controller_params\nwait_controller\n\n{{- with .Values.configurator.controller }}\n{{- with .props }}\nconfigure_controller_props {{ mustToJson . | quote }}\n{{- end }}\n\n{{- $selectFilter := dict }}\n{{- range .resourceGroups }}\n{{- range $k, $v := .selectFilter }}\n{{- $_ := set $selectFilter (snakecase $k) $v }}\n{{- end }}\nconfigure_resource_group {{ required \"A valid .Values.configurator.controller.resourceGroups[].name entry required!\" .name | quote }} {{ mustToJson $selectFilter | quote }} {{ mustToJson (.props | default (dict)) | quote }}\n{{- $rg_name := .name }}\n{{- range .volumeGroups }}\nconfigure_volume_group {{ $rg_name | quote }} {{ required \"A valid .Values.configurator.controller.resourceGroups[].volumeGroups[].volumeNumber entry required!\" .volumeNumber | quote }} {{ mustToJson (.props | default (dict)) | quote }}\n{{- end }}\n{{- end }}\n{{- end }}\n\nfinish\n": parse error in "linstor/templates/configurator-configmap.yaml": template: linstor/templates/configurator-configmap.yaml:10: function "mustToJson" not defined : exit status 1; waiting on helm-controller_c-8h99v`

Previous versions works good!

I´m on Kubernets 1.20.6

Thanks for this awesome project!!

**Comment by kvaps** [comment]
Hi, could you provide your helm version?
```
helm version
```

**Comment by bratao** [comment]
> 
> 
> Hi, could you provide your helm version?
> 
> ```
> helm version
> ```

@kvaps sure, 

`version.BuildInfo{Version:"v3.3.3-rancher3", GitCommit:"657df59bbba1d9e175cf5080d4885bd57d037906", GitTreeState:"clean", GoVersion:"go1.13.15"}`

**Comment by kvaps** [comment]
Weird, it was working to me on official `v3.3.3`.
Any way, I'm trying to keep compatibility with the older versions and do not drop it with no specific reason.

I believe that **mustToJson** is not that reason, fixed in ad0211541c623f2a1db06285e32f7ebd6973d3da
