### ISSUE TITLE
Add labels to controller service

### ISSUE THREAD

**Issue by fondemen** [kvaps/kube-linstor#40]
Hello!
I'm monitoring my linstor deployment using prometheus. To do so, I'd need to label my controller service. So far, I'm using the following command line : `kubectl -n linstor label svc linstor-controller app=linstor-controller-metrics`.
It would be great if this could be done the same way it is possible to add annotations (`.Values.controller.service.annotations`)

**Comment by kvaps** [comment]
fixed in `v0.13.0`, thank you
