### ISSUE TITLE
image "ghcr.io/kvaps/linstor-stork:v1.12.5" not found

### ISSUE THREAD

**Issue by fngx** [kvaps/kube-linstor#42]
Trying out this project, as it ought to be simpler in comparison with piraeus,

looks like [values.yml](https://github.com/kvaps/kube-linstor/blob/f0e672e2974f96ff4868dafb8bdf23507396aeed/helm/kube-linstor/values.yaml#L258) version of stork should be v1.12.3 to me

thanks,

**Comment by kvaps** [comment]
Okay, there is some problems with the building, there is no changes so I just retaged previous image. 
Thank you for the report!
