### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by fondemen** [kvaps/kube-linstor#53]
Hello,
Is there a plan to integrate latest versions of Linstor ? So far, the chart and available images are 1.14 while 1.17 is already there.
I've got the feeling that Piraeus is more on focus now. In case this chart has no plan to keep up with latest versions, is there any migration guide to Piraeus (including for those who are using Postgres) ?
Anyway, thanks for this piece of work !
Cheers !

**Comment by kvaps** [comment]
Hi, thank you for the question.

Right now I pushing many changes from this project to Piraeus-operator, eg. automatic SSL certificates generation, Stork and so on. I think now it is quite stable to start using it.

Of course I'm going to write the migration guide after all my changes will be merged to upstream.

I think that migration between both projects should be very simple:

1. preserve your database connection values:
   ```
   helm get values linstor -n linstor
   ```
2. uninstall kube-linstor chart:
   ```
   helm uninstall linstor -n linstor
   ```
3. install piraeus chart:
   ```
   git clone https://github.com/piraeusdatastore/piraeus-operator
   cd piraeus-operator
   helm install piraeus-op ./charts/piraeus -n linstor \
     --set etcd.enabled=false \
     --set "operator.controller.dbConnectionURL=jdbc:postgresql://linstor-db-stolon-proxy/linstor?user=postgresadmin&password=admin123"
   ```
   where:
   - `jdbc:postgresql://linstor-db-stolon-proxy/linstor` - your previous `connectionUrl`
   - `postgresadmin` - your database user
   - `admin123` - your database password

Note that current version of piraeus-operator does not support the above features yet.
I would be very grateful if you try this method.

**Comment by fondemen** [comment]
Hello, thanks for the fast answer!

I tested your solution. It works great given the host is [properly prepared](https://github.com/piraeusdatastore/piraeus-operator/blob/master/doc/host-setup.md#install-drbd-on-the-host) by executing on each node:
```
echo -n "disabled" > /sys/module/drbd/parameters/usermode_helper
echo "options drbd usermode_helper=disabled" > /etc/modprobe.d/drbd.conf
```

Regarding stork, I was beaten by https://github.com/piraeusdatastore/piraeus-operator/issues/205 (`Error: unknown flag: --scheduler-name` - I'm using K8s 1.23), but this was already the case when using kvaps/kube-linstor... So I had to add `--set stork.schedulerTag=v1.21.9`.

I think it's really nice to be able to switch to piraeus without abandoning any feature you offered in this repo, great job !

**Comment by fondemen** [comment]
New command to get access to the linstor cli : `alias linstor="kubectl exec -n linstor $(kubectl -n linstor get pod -l app.kubernetes.io/name=piraeus-controller -o jsonpath=\"{.items[0].metadata.name}\") -c linstor-controller -- linstor"`

**Comment by kvaps** [comment]
Actually there is ready plugin for that https://github.com/piraeusdatastore/kubectl-linstor/

**Comment by kvaps** [comment]
I added the warning to project page with link to this issue
/close
