### ISSUE TITLE
Stork 2.6.4 is incompatible with Kubernetes >=1.22

### ISSUE THREAD

**Issue by russelhowe** [kvaps/kube-linstor#54]
Upgrading to Stork 2.8.2 by changing the version in the `dockerfiles/linstor-stork/Dockerfile` gets things working. Should I provide a PR or do you explicitly not support newer versions?

**Comment by kvaps** [comment]
Hi, if this works for you, then please provide a PR.

Also I made a fix for stork, it might be necessary to enable SSL support, but it is not merged yet
https://github.com/libopenstorage/stork/pull/1032

**Comment by kvaps** [comment]
Hi, I made a fork of stork which contains only scheduler extender functionality:
https://github.com/kvaps/linstor-scheduler-extender

More details in this issue: https://github.com/piraeusdatastore/piraeus-operator/issues/270
FYI
