### ISSUE TITLE
Add ZFS storage provider support

### ISSUE THREAD

**Issue by it-svit** [kvaps/kube-linstor#6]
Currently when you run 

```
linstor node create node1 xxx.xxx.xxx.xxx
```

the following warning is shown:

```
    Unsupported storage providers:
        ZFS: 'cat /sys/module/zfs/version' returned with exit code 1
        ZFS_THIN: 'cat /sys/module/zfs/version' returned with exit code 1
```

**Comment by kvaps** [comment]
Wouldn't be enough to add `/sys/module` mount to [linstor-satellite.yaml](https://github.com/kvaps/kube-linstor/blob/master/helm/kube-linstor/templates/linstor-satellite.yaml) volumes and volumeMounts?

**Comment by it-svit** [comment]
It might be better to mount `/sys/module/zfs` only.
Also this option should be switchable using chart variables.
Because if there are no ZFS (`zfsutils-linux` for Ubutnu 18.04) installed - linstor-satellite container won't start.
```
  Warning  Failed     9s (x3 over 23s)  kubelet, node4     Error: failed to start container "linstor-satellite": Error response from daemon: error while creating mount source path '/sys/module/zfs': mkdir /sys/module/zfs: operation not permitted
```

It is also necessary to update README.md with ZFS prerequisite and guide how to turn ZFS support on and off.

Because ZFS might be not required in each installation.

**Comment by kvaps** [comment]
Yes, but we're providing zfs-utils package in the common linstor-satellite docker image and `/sys/modules` path existing in every Linux-system regardless of using zfs on the host itself.
So why not simple use it in common way?

Can you confirm that this change is enough for make zfs working on the Linstor?

**Comment by it-svit** [comment]
I was hoping someone else would test whole ZFS case and add required updates :)

I'd be able to test it next week, so no fast reply should be expected.
